name: Deploy

on: [push]

jobs:
  build:

    if: "contains(github.event.head_commit.message, '[deploy beta]')"

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:   
        channel: 'dev'

    - name: Build
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
            echo $KEY_JKS > key.jks
            flutter pub get
            flutter packages pub run build_runner build --delete-conflicting-outputs
            flutter build apk --release
      
    - name: Static analysis
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Deploy Android app to Firebase App Distribution
      if: success() || failure() 
      uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: all
        file: build/app/outputs/apk/release/app-release.apk

    # - name: Build iOS app
    #   run: flutter build ios

    # - name: Deploy iOS app to Firebase App Distribution
    #   uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
    #   with:
    #     appId: ${{secrets.FIREBASE_IOS_APP_ID}}
    #     token: ${{secrets.FIREBASE_TOKEN}}
    #     groups: all
    #     file: build/ios/iphoneos/Runner.app
